package com.huijie.demo.mapper;

import com.huijie.demo.model.SysOperationLog;

public interface SysOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbg.generated
     */
    int insert(SysOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbg.generated
     */
    int insertSelective(SysOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbg.generated
     */
    SysOperationLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysOperationLog record);
}