package com.guns.demo.mapper;

import com.guns.demo.model.SysExpense;

public interface SysExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbg.generated
     */
    int insert(SysExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbg.generated
     */
    int insertSelective(SysExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbg.generated
     */
    SysExpense selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_expense
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysExpense record);
}