package com.guns.demo.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_dept
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysDept {
    /** 主键id*/
    private Integer id;

    /** 排序*/
    private Integer num;

    /** 父部门id*/
    private Integer pid;

    /** 父级ids*/
    private String pids;

    /** 简称*/
    private String simplename;

    /** 全称*/
    private String fullname;

    /** 提示*/
    private String tips;

    /** 版本（乐观锁保留字段）*/
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.id
     *
     * @return the value of sys_dept.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.id
     *
     * @param id the value for sys_dept.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.num
     *
     * @return the value of sys_dept.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.num
     *
     * @param num the value for sys_dept.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.pid
     *
     * @return the value of sys_dept.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.pid
     *
     * @param pid the value for sys_dept.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.pids
     *
     * @return the value of sys_dept.pids
     *
     * @mbg.generated
     */
    public String getPids() {
        return pids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.pids
     *
     * @param pids the value for sys_dept.pids
     *
     * @mbg.generated
     */
    public void setPids(String pids) {
        this.pids = pids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.simplename
     *
     * @return the value of sys_dept.simplename
     *
     * @mbg.generated
     */
    public String getSimplename() {
        return simplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.simplename
     *
     * @param simplename the value for sys_dept.simplename
     *
     * @mbg.generated
     */
    public void setSimplename(String simplename) {
        this.simplename = simplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.fullname
     *
     * @return the value of sys_dept.fullname
     *
     * @mbg.generated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.fullname
     *
     * @param fullname the value for sys_dept.fullname
     *
     * @mbg.generated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.tips
     *
     * @return the value of sys_dept.tips
     *
     * @mbg.generated
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.tips
     *
     * @param tips the value for sys_dept.tips
     *
     * @mbg.generated
     */
    public void setTips(String tips) {
        this.tips = tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.version
     *
     * @return the value of sys_dept.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.version
     *
     * @param version the value for sys_dept.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}