package com.guns.demo.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_notice
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysNotice {
    /** 主键*/
    private Integer id;

    /** 标题*/
    private String title;

    /** 类型*/
    private Integer type;

    /** 创建时间*/
    private Date createtime;

    /** 创建人*/
    private Integer creater;

    /** 内容*/
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.id
     *
     * @return the value of sys_notice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.id
     *
     * @param id the value for sys_notice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.title
     *
     * @return the value of sys_notice.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.title
     *
     * @param title the value for sys_notice.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.type
     *
     * @return the value of sys_notice.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.type
     *
     * @param type the value for sys_notice.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.createtime
     *
     * @return the value of sys_notice.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.createtime
     *
     * @param createtime the value for sys_notice.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.creater
     *
     * @return the value of sys_notice.creater
     *
     * @mbg.generated
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.creater
     *
     * @param creater the value for sys_notice.creater
     *
     * @mbg.generated
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.content
     *
     * @return the value of sys_notice.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.content
     *
     * @param content the value for sys_notice.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}