package com.guns.demo.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_relation
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysRelation {
    /** 主键*/
    private Integer id;

    /** 菜单id*/
    private Long menuid;

    /** 角色id*/
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_relation.id
     *
     * @return the value of sys_relation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_relation.id
     *
     * @param id the value for sys_relation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_relation.menuid
     *
     * @return the value of sys_relation.menuid
     *
     * @mbg.generated
     */
    public Long getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_relation.menuid
     *
     * @param menuid the value for sys_relation.menuid
     *
     * @mbg.generated
     */
    public void setMenuid(Long menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_relation.roleid
     *
     * @return the value of sys_relation.roleid
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_relation.roleid
     *
     * @param roleid the value for sys_relation.roleid
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}