package com.huijie.demo.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_expense
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysExpense {
    /** */
    private Integer id;

    /** 报销金额*/
    private BigDecimal money;

    /** 描述*/
    private String desc;

    /** */
    private Date createtime;

    /** 状态: 1.待提交  2:待审核   3.审核通过 4:驳回*/
    private Integer state;

    /** 用户id*/
    private Integer userid;

    /** 流程定义id*/
    private String processid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_expense.id
     *
     * @return the value of sys_expense.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_expense.id
     *
     * @param id the value for sys_expense.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_expense.money
     *
     * @return the value of sys_expense.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_expense.money
     *
     * @param money the value for sys_expense.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_expense.desc
     *
     * @return the value of sys_expense.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_expense.desc
     *
     * @param desc the value for sys_expense.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_expense.createtime
     *
     * @return the value of sys_expense.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_expense.createtime
     *
     * @param createtime the value for sys_expense.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_expense.state
     *
     * @return the value of sys_expense.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_expense.state
     *
     * @param state the value for sys_expense.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_expense.userid
     *
     * @return the value of sys_expense.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_expense.userid
     *
     * @param userid the value for sys_expense.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_expense.processId
     *
     * @return the value of sys_expense.processId
     *
     * @mbg.generated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_expense.processId
     *
     * @param processid the value for sys_expense.processId
     *
     * @mbg.generated
     */
    public void setProcessid(String processid) {
        this.processid = processid;
    }
}