package com.huijie.demo.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_login_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysLoginLog {
    /** 主键*/
    private Integer id;

    /** 日志名称*/
    private String logname;

    /** 管理员id*/
    private Integer userid;

    /** 创建时间*/
    private Date createtime;

    /** 是否执行成功*/
    private String succeed;

    /** 登录ip*/
    private String ip;

    /** 具体消息*/
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.id
     *
     * @return the value of sys_login_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.id
     *
     * @param id the value for sys_login_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.logname
     *
     * @return the value of sys_login_log.logname
     *
     * @mbg.generated
     */
    public String getLogname() {
        return logname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.logname
     *
     * @param logname the value for sys_login_log.logname
     *
     * @mbg.generated
     */
    public void setLogname(String logname) {
        this.logname = logname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.userid
     *
     * @return the value of sys_login_log.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.userid
     *
     * @param userid the value for sys_login_log.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.createtime
     *
     * @return the value of sys_login_log.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.createtime
     *
     * @param createtime the value for sys_login_log.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.succeed
     *
     * @return the value of sys_login_log.succeed
     *
     * @mbg.generated
     */
    public String getSucceed() {
        return succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.succeed
     *
     * @param succeed the value for sys_login_log.succeed
     *
     * @mbg.generated
     */
    public void setSucceed(String succeed) {
        this.succeed = succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.ip
     *
     * @return the value of sys_login_log.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.ip
     *
     * @param ip the value for sys_login_log.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.message
     *
     * @return the value of sys_login_log.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.message
     *
     * @param message the value for sys_login_log.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message;
    }
}