package com.huijie.demo.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_operation_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysOperationLog {
    /** 主键*/
    private Integer id;

    /** 日志类型*/
    private String logtype;

    /** 日志名称*/
    private String logname;

    /** 用户id*/
    private Integer userid;

    /** 类名称*/
    private String classname;

    /** 创建时间*/
    private Date createtime;

    /** 是否成功*/
    private String succeed;

    /** 方法名称*/
    private String method;

    /** 备注*/
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.id
     *
     * @return the value of sys_operation_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.id
     *
     * @param id the value for sys_operation_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.logtype
     *
     * @return the value of sys_operation_log.logtype
     *
     * @mbg.generated
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.logtype
     *
     * @param logtype the value for sys_operation_log.logtype
     *
     * @mbg.generated
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.logname
     *
     * @return the value of sys_operation_log.logname
     *
     * @mbg.generated
     */
    public String getLogname() {
        return logname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.logname
     *
     * @param logname the value for sys_operation_log.logname
     *
     * @mbg.generated
     */
    public void setLogname(String logname) {
        this.logname = logname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.userid
     *
     * @return the value of sys_operation_log.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.userid
     *
     * @param userid the value for sys_operation_log.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.classname
     *
     * @return the value of sys_operation_log.classname
     *
     * @mbg.generated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.classname
     *
     * @param classname the value for sys_operation_log.classname
     *
     * @mbg.generated
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.createtime
     *
     * @return the value of sys_operation_log.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.createtime
     *
     * @param createtime the value for sys_operation_log.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.succeed
     *
     * @return the value of sys_operation_log.succeed
     *
     * @mbg.generated
     */
    public String getSucceed() {
        return succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.succeed
     *
     * @param succeed the value for sys_operation_log.succeed
     *
     * @mbg.generated
     */
    public void setSucceed(String succeed) {
        this.succeed = succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.method
     *
     * @return the value of sys_operation_log.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.method
     *
     * @param method the value for sys_operation_log.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.message
     *
     * @return the value of sys_operation_log.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.message
     *
     * @param message the value for sys_operation_log.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message;
    }
}